/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SrtEditorGUI.java
 *
 * Created on Jan 3, 2012, 11:31:00 PM
 */
package srtEditor.ui;

import java.io.File;
import javax.swing.JFileChooser;
import srtEditor.srtfiles.SrtFile;
import srtEditor.srtfiles.srtEntry.TimeObject;

/**
 *
 * @author tjen
 */
public class SrtEditorPanel_txtFieldOut extends javax.swing.JPanel
{

    SrtFile sf = new SrtFile();
    boolean opening = false;
    boolean saving = false;

    /** Creates new form SrtEditorGUI */
    public SrtEditorPanel_txtFieldOut()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTime = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnSetLater = new javax.swing.JButton();
        btnScale = new javax.swing.JButton();
        labelTxtTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInputOutput = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(426, 513));

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnSetLater.setText("Set Later");
        btnSetLater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLaterActionPerformed(evt);
            }
        });

        btnScale.setText("Scale");
        btnScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScaleActionPerformed(evt);
            }
        });

        labelTxtTime.setText("offset time(milliseconds)/scale:");

        txtInputOutput.setColumns(20);
        txtInputOutput.setRows(5);
        jScrollPane1.setViewportView(txtInputOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnRead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(btnPrint))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSetLater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(btnScale))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelTxtTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRead)
                    .addComponent(btnPrint))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetLater)
                    .addComponent(btnScale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReadActionPerformed
    {//GEN-HEADEREND:event_btnReadActionPerformed
        // add your handling code here:
        sf.readFromString(txtInputOutput.getText());
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPrintActionPerformed
    {//GEN-HEADEREND:event_btnPrintActionPerformed
        // add your handling code here:
        txtInputOutput.setText(sf.toString());
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSetLaterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSetLaterActionPerformed
    {//GEN-HEADEREND:event_btnSetLaterActionPerformed
        sf.setLater(TimeObject.getInstance(Long.parseLong(txtTime.getText())));
    }//GEN-LAST:event_btnSetLaterActionPerformed

    private void btnScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnScaleActionPerformed
    {//GEN-HEADEREND:event_btnScaleActionPerformed
        sf.scale(Double.parseDouble(txtTime.getText()));
    }//GEN-LAST:event_btnScaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnScale;
    private javax.swing.JButton btnSetLater;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTxtTime;
    private javax.swing.JTextArea txtInputOutput;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
