/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SrtEditorGUI.java
 *
 * Created on Jan 3, 2012, 11:31:00 PM
 */
package srtEditor.ui;

import java.io.File;
import javax.swing.JFileChooser;
import srtEditor.srtfiles.SrtFile;
import srtEditor.srtfiles.srtEntry.TimeObject;

/**
 *
 * @author tjen
 */
public class SrtEditorPanel extends javax.swing.JPanel
{

    SrtFile sf = new SrtFile();
    boolean opening = false;
    boolean saving = false;

    /** Creates new form SrtEditorGUI */
    public SrtEditorPanel()
    {
        initComponents();
        fileChooser.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTime = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSetLater = new javax.swing.JButton();
        btnScale = new javax.swing.JButton();
        labelTxtTime = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();

        setMinimumSize(new java.awt.Dimension(426, 513));

        btnOpen.setText("Open File");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnSave.setText("Save File");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSetLater.setText("Set Later");
        btnSetLater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLaterActionPerformed(evt);
            }
        });

        btnScale.setText("Scale");
        btnScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScaleActionPerformed(evt);
            }
        });

        labelTxtTime.setText("offset time(milliseconds)/scale:");

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSetLater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(btnScale))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTxtTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 402, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen)
                    .addComponent(btnSave))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetLater)
                    .addComponent(btnScale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenActionPerformed
    {//GEN-HEADEREND:event_btnOpenActionPerformed
        // add your handling code here:
        opening = true;
        saving = false;
        fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
        fileChooser.setVisible(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        // add your handling code here:
        opening = false;
        saving = true;
        fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
        fileChooser.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSetLaterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSetLaterActionPerformed
    {//GEN-HEADEREND:event_btnSetLaterActionPerformed
        sf.setLater(TimeObject.getInstance(Long.parseLong(txtTime.getText())));
    }//GEN-LAST:event_btnSetLaterActionPerformed

    private void btnScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnScaleActionPerformed
    {//GEN-HEADEREND:event_btnScaleActionPerformed
        sf.scale(Double.parseDouble(txtTime.getText()));
    }//GEN-LAST:event_btnScaleActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fileChooserActionPerformed
    {//GEN-HEADEREND:event_fileChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION))
        {
            File selectedFile = fileChooser.getSelectedFile();
            if (saving)
            {
                sf.writeToFile(selectedFile);
            } else if (opening)
            {
                sf.readFromFile(selectedFile);
            }
        }
        saving = false;
        opening = false;
        fileChooser.setVisible(false);
    }//GEN-LAST:event_fileChooserActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnScale;
    private javax.swing.JButton btnSetLater;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel labelTxtTime;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
